stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .  --cpuset-cpus="0-3"
      tag: demandcluster/bulldog:v1
      pushRemote: true
      registry: harbor.demandcluster.com
timeout: 60
notification: {}
